-- MySQL Script generated by MySQL Workbench
-- Wed Nov 14 14:06:23 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`VIVEROS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VIVEROS` (
  `coord` FLOAT NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`coord`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ZONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ZONA` (
  `coord` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `productividad` FLOAT NULL,
  PRIMARY KEY (`coord`, `nombre`),
  CONSTRAINT `fk_zona`
    FOREIGN KEY (`coord`)
    REFERENCES `mydb`.`VIVEROS` (`coord`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMPLEADO` (
  `dni` VARCHAR(9) NOT NULL,
  `css` INT NOT NULL,
  `sueldo` FLOAT NULL,
  `antigüedad` DATE NULL,
  `productividad` FLOAT NULL,
  `coordenada` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `fecha_final` DATE NULL,
  `fecha_inicio` DATE NULL,
  `venta` FLOAT NULL,
  PRIMARY KEY (`dni`, `nombre`, `coordenada`),
  UNIQUE INDEX `css_UNIQUE` (`css` ASC),
  INDEX `coordenada_idx` (`coordenada` ASC, `nombre` ASC),
  CONSTRAINT `variables`
    FOREIGN KEY (`coordenada` , `nombre`)
    REFERENCES `mydb`.`ZONA` (`coord` , `nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCTO` (
  `codigo` VARCHAR(45) NOT NULL,
  `stock` INT NULL,
  `precio` FLOAT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE` (
  `dni` VARCHAR(45) NOT NULL,
  `bonificación` FLOAT NULL,
  `total_mes` INT NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCTO_EMPLEADO_CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUCTO_EMPLEADO_CLIENTE` (
  `dni_empleado` VARCHAR(45) NOT NULL,
  `dni_cliente` VARCHAR(45) NOT NULL,
  `codigo_producto` VARCHAR(45) NOT NULL,
  `cantidad` INT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`dni_empleado`, `dni_cliente`, `codigo_producto`, `fecha`),
  INDEX `codigo_producto_idx` (`codigo_producto` ASC),
  INDEX `dni_cliente_idx` (`dni_cliente` ASC),
  CONSTRAINT `dni_empleado`
    FOREIGN KEY (`dni_empleado`)
    REFERENCES `mydb`.`EMPLEADO` (`dni`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `codigo_producto`
    FOREIGN KEY (`codigo_producto`)
    REFERENCES `mydb`.`PRODUCTO` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `dni_cliente`
    FOREIGN KEY (`dni_cliente`)
    REFERENCES `mydb`.`CLIENTE` (`dni`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
