-- MySQL Script generated by MySQL Workbench
-- Sun Nov 25 18:02:35 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

#SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
#SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
#SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
#CREATE SCHEMA IF NOT EXISTS mydb DEFAULT CHARACTER SET utf8 ;
#USE mydb ;

-- -----------------------------------------------------
-- Table Medicamento
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Medicamento (
  cod_medicamento INT NOT NULL,
  nombre VARCHAR(45) NOT NULL,
  stock INT NOT NULL,
  precio FLOAT NOT NULL,
  tipo VARCHAR(45) NOT NULL,
  vendidos INT NOT NULL,
  tipo_receta VARCHAR(45) NOT NULL,
  PRIMARY KEY (cod_medicamento));

CREATE UNIQUE INDEX nombre_UNIQUE ON Medicamento (nombre);


-- -----------------------------------------------------
-- Table Laboratorio
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Laboratorio (
  cod_laboratorio INT NOT NULL,
  nombre VARCHAR(45) NOT NULL,
  direccion VARCHAR(45) NOT NULL,
  telefono INT NOT NULL,
  fax INT NULL,
  contacto VARCHAR(45) NULL,
  PRIMARY KEY (cod_laboratorio));

CREATE UNIQUE INDEX nombre_lab_UNIQUE ON Laboratorio (nombre);


-- -----------------------------------------------------
-- Table Cliente_credito
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Cliente_credito (
  dni VARCHAR(45) NOT NULL,
  datos_bancarios VARCHAR(45) NOT NULL,
  PRIMARY KEY (dni));


-- -----------------------------------------------------
-- Table Familia
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Familia (
  enfermedad INT NOT NULL,
  PRIMARY KEY (enfermedad));


-- -----------------------------------------------------
-- Table Compra
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Compra (
  cod_compra INT NOT NULL,
  PRIMARY KEY (cod_compra));


-- -----------------------------------------------------
-- Table Compra_cliente_credito
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Compra_cliente_credito (
  dni VARCHAR(45) NOT NULL,
  cod_compra INT NOT NULL,
  cantidad_ventas INT NOT NULL,
  fecha_compra DATE NOT NULL,
  PRIMARY KEY (dni, cod_compra),
  CONSTRAINT fk_dni
    FOREIGN KEY (dni)
    REFERENCES Cliente_credito (dni)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_cod_compra
    FOREIGN KEY (cod_compra)
    REFERENCES Compra (cod_compra)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE INDEX fk_cod_compra_idx ON Compra_cliente_credito (cod_compra);


-- -----------------------------------------------------
-- Table Medicamento_compra
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Medicamento_compra (
  cod_compra INT NOT NULL,
  cod_medicamento INT NOT NULL,
  PRIMARY KEY (cod_compra, cod_medicamento),
  CONSTRAINT fk_compra
    FOREIGN KEY (cod_compra)
    REFERENCES Compra (cod_compra)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_med
    FOREIGN KEY (cod_medicamento)
    REFERENCES Medicamento (cod_medicamento)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE INDEX fk_med_idx ON Medicamento_compra (cod_medicamento);


-- -----------------------------------------------------
-- Table Medicamento_lab
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Medicamento_lab (
  cod_laboratorio INT NOT NULL,
  cod_medicamento INT NOT NULL,
  PRIMARY KEY (cod_laboratorio, cod_medicamento),
  CONSTRAINT fk_medicamento_lab
    FOREIGN KEY (cod_laboratorio)
    REFERENCES Laboratorio (cod_laboratorio)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_lab_medicamento
    FOREIGN KEY (cod_medicamento)
    REFERENCES Medicamento (cod_medicamento)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE INDEX fk_lab_medicamento_idx ON Medicamento_lab (cod_medicamento);


-- -----------------------------------------------------
-- Table Medicamento_familia
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS Medicamento_familia (
  enfermedad INT NOT NULL,
  cod_medicamento INT NOT NULL,
  PRIMARY KEY (enfermedad, cod_medicamento),
  CONSTRAINT fk_familia
    FOREIGN KEY (enfermedad)
    REFERENCES Familia (enfermedad)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_medicamento
    FOREIGN KEY (cod_medicamento)
    REFERENCES Medicamento (cod_medicamento)
    ON DELETE CASCADE
    ON UPDATE CASCADE);

CREATE INDEX fk_medicamento_idx ON Medicamento_familia (cod_medicamento);


#SET SQL_MODE=@OLD_SQL_MODE;
#SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
#SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
